# Find the Difference
# You are given two strings s and t.
# String t is generated by random shuffling string s and then add one more letter at a random position.
# Return the letter that was added to t.

def findTheDifference (s, t) :
    sValue, tValue = 0, 0
    for ch in s :
        sValue += ord(ch)
    for ch in t :
        tValue += ord(ch)
    return chr(tValue-sValue)
print(findTheDifference(s = "abcd", t = "abcde"))